spring.application.name=api-gateway
server.port=8090

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Gateway - Eureka Discovery
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Explicit Routes
spring.cloud.gateway.server.webflux.routes[0].id=order-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/orders/**

spring.cloud.gateway.server.webflux.routes[1].id=inventory-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/inventory/**

spring.cloud.gateway.server.webflux.routes[2].id=payment-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payments/**

# Actuator
management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.gateway.access=read-only
# JWT Resource Server
spring.security.oauth2.resourceserver.jwt.secret-key=${JWT_SECRET}
