apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: zaalima/order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://service-registry:8761/eureka/
            - name: EUREKA_INSTANCE_HOSTNAME
              value: order-service
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://config-server:8888
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.docker.internal:5432/orders_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 8081
      targetPort: 8081
  type: ClusterIP
