spring.application.name=config-server
server.port=8888

# Eureka registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Native Config Repository
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:${CONFIG_REPO_PATH}